export const DISPLAY = 'flex'
export const FLEX_COL = 'flex-col'
export const FLEX_ROW = 'flex-row'
export const RECT_SIZE_AUTO = 'flex-auto'
export const FLEX_NOT_SCALE = 'flex-shrink-0'
export const FLEX_MAIN_AXIS = 'flex-basis'
export const POS_REL = 'relative'
export const POS_FIX = 'fixed'
export const POS_ABS = 'absolute'
export const LAYOUT_NAMES = [FLEX_COL, FLEX_ROW]
export const POS_NAMES = [POS_REL, POS_ABS, POS_FIX]
